# Generated by Django 3.1 on 2021-12-16 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miejscowosc', models.CharField(max_length=200, verbose_name='City')),
                ('ulica', models.CharField(max_length=200, verbose_name='Street')),
                ('numer_domu', models.CharField(max_length=200, verbose_name='House number')),
                ('kod_pocztowy', models.CharField(max_length=200, verbose_name='Postal code')),
            ],
            options={
                'verbose_name': 'Adress',
                'verbose_name_plural': 'Adress',
            },
        ),
        migrations.CreateModel(
            name='KartaPracownika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identyfikator', models.CharField(max_length=200, verbose_name='Identificatior')),
                ('opis', models.CharField(max_length=200, verbose_name='Description')),
                ('uwagi', models.CharField(max_length=200, verbose_name='Addontation')),
                ('data', models.DateTimeField(verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Employee Cards',
                'verbose_name_plural': 'Employee Cards',
            },
        ),
        migrations.CreateModel(
            name='OcenaPracownika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.IntegerField(default=0, verbose_name='Rating')),
                ('kryteria', models.TextField(verbose_name='Criteria')),
                ('opis', models.CharField(max_length=200, verbose_name='Description')),
                ('data_wydania', models.DateTimeField(verbose_name='Release date')),
                ('data_oceny', models.DateTimeField(verbose_name='Rating date')),
            ],
            options={
                'verbose_name': 'Ratrings',
                'verbose_name_plural': 'Ratrings',
            },
        ),
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=200, verbose_name='First name')),
                ('drugie_imie', models.CharField(max_length=200, verbose_name='Secound name')),
                ('nazwisko', models.CharField(max_length=200, verbose_name='Surname')),
                ('nazwisko_panienskie', models.CharField(max_length=200, verbose_name='Maiden name')),
                ('pesel', models.IntegerField(default=0, verbose_name='PESEL')),
                ('numer_dowodu', models.CharField(max_length=200, verbose_name='Document ID')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('numer_telefonu', models.IntegerField(verbose_name='Phone number')),
                ('stan_cywilny', models.CharField(max_length=200, verbose_name='Marital status')),
                ('ile_dzieci', models.IntegerField(verbose_name='How many kids?')),
                ('niepelnosprawnosc', models.BooleanField(verbose_name='Is disabled?')),
                ('numer_konta_bankowego', models.IntegerField(verbose_name='Bank account number')),
                ('adres', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment_and_payments.adres', verbose_name='Employee Adress')),
                ('karta_pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment_and_payments.kartapracownika', verbose_name='Employee Card')),
                ('ocena_pracownik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment_and_payments.ocenapracownika', verbose_name='Employee Rating')),
            ],
            options={
                'verbose_name': 'Employees',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Stanowisko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200, verbose_name='Name')),
                ('opis', models.CharField(max_length=200, verbose_name='Description')),
                ('wymagania', models.CharField(max_length=200, verbose_name='Requirements')),
                ('kod_dzialu', models.IntegerField(default=0, verbose_name='Departament code')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Position',
            },
        ),
        migrations.CreateModel(
            name='Szkolenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200, verbose_name='Name')),
                ('opis', models.CharField(max_length=200, verbose_name='Description')),
                ('data_rozpoczecia', models.DateTimeField(verbose_name='From date')),
                ('data_zakonczenia', models.DateTimeField(verbose_name='To date')),
                ('ilosc_miejsc', models.IntegerField(default=0, verbose_name='How many places?')),
                ('koszt', models.IntegerField(default=0, verbose_name='Cost')),
                ('zrodlo_finansowania', models.CharField(max_length=200, verbose_name='Source of financing')),
                ('organizator', models.CharField(max_length=200, verbose_name='Organizer')),
                ('miejsce', models.CharField(max_length=200, verbose_name='Place')),
                ('delegacja', models.BooleanField(verbose_name='Is delegation?')),
                ('typ', models.CharField(max_length=200, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Courses',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Ubezpieczenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.CharField(max_length=200, verbose_name='Number')),
                ('rodzaj_ubezpieczenia', models.CharField(max_length=200, verbose_name='Type of issurance')),
                ('data_od', models.DateTimeField(verbose_name='From date')),
                ('data_do', models.DateTimeField(verbose_name='To date')),
            ],
            options={
                'verbose_name': 'Insurances',
                'verbose_name_plural': 'Insurances',
            },
        ),
        migrations.CreateModel(
            name='Wyksztalcenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=200, verbose_name='Type')),
                ('opis', models.CharField(max_length=200, verbose_name='Description')),
                ('data_uzyskania', models.DateTimeField(verbose_name='Obtaining date')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
            },
        ),
        migrations.CreateModel(
            name='ZwolnienieLekarskie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=200, verbose_name='Description')),
                ('data_rozpoczecia', models.DateTimeField(verbose_name='From date')),
                ('data_wydania', models.DateTimeField(verbose_name='Release date')),
                ('kod_choroby', models.IntegerField(default=0, verbose_name='Sickness code')),
                ('wystawiajacy', models.CharField(max_length=200, verbose_name='Signed By')),
                ('pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment_and_payments.pracownik', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Sick Leaves',
                'verbose_name_plural': 'Sick Leaves',
            },
        ),
        migrations.CreateModel(
            name='Zadania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200, verbose_name='Name')),
                ('opis', models.CharField(max_length=200, verbose_name='Description')),
                ('godzinowy_czas_trwania', models.IntegerField(default=0, verbose_name='Period count in hours')),
                ('procentowy_udzial_w_zadaniu', models.IntegerField(default=0, verbose_name='Usage in percentage')),
                ('ilu_pracownikow', models.IntegerField(default=0, verbose_name='How many employees')),
                ('pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment_and_payments.pracownik', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Tasks',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='Urlop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rozpoczecia', models.DateTimeField(verbose_name='From date')),
                ('data_wydania', models.DateTimeField(verbose_name='Release date')),
                ('kwota', models.IntegerField(default=0, verbose_name='Price')),
                ('rodzaj', models.CharField(max_length=200, verbose_name='Kind')),
                ('pozostalo', models.IntegerField(default=0, verbose_name='Remaining')),
                ('pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment_and_payments.pracownik', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Vacations',
                'verbose_name_plural': 'Vacations',
            },
        ),
        migrations.CreateModel(
            name='Umowa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zawarcia', models.DateTimeField(verbose_name='From date')),
                ('data_rozwiazania', models.DateTimeField(verbose_name='To date')),
                ('wynagrodzenie', models.IntegerField(default=0, verbose_name='Payment')),
                ('opis', models.CharField(max_length=200, verbose_name='Description')),
                ('pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment_and_payments.pracownik', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Contracts',
                'verbose_name_plural': 'Contracts',
            },
        ),
        migrations.CreateModel(
            name='PrzypisaniNaSzkolenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=200, verbose_name='Description')),
                ('czy_aktywny', models.BooleanField(verbose_name='Is active?')),
                ('pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment_and_payments.pracownik', verbose_name='Employee')),
                ('szkolenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment_and_payments.szkolenie', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Assigned to course',
                'verbose_name_plural': 'Assigned to course',
            },
        ),
        migrations.CreateModel(
            name='Premia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=200, verbose_name='Type')),
                ('opis', models.CharField(max_length=200, verbose_name='Description')),
                ('wielkosc', models.IntegerField(default=0, verbose_name='Value')),
                ('umowa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment_and_payments.umowa', verbose_name='Contract')),
            ],
            options={
                'verbose_name': 'Bonuses',
                'verbose_name_plural': 'Bonuses',
            },
        ),
        migrations.AddField(
            model_name='pracownik',
            name='stanowisko',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment_and_payments.stanowisko', verbose_name='Employee Position'),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='ubezpieczenie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment_and_payments.ubezpieczenie', verbose_name='Employee Issurance'),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='wyksztalcenie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment_and_payments.wyksztalcenie', verbose_name='Employee Education'),
        ),
        migrations.CreateModel(
            name='Nagrody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=200, verbose_name='Description')),
                ('kryteria', models.TextField(verbose_name='Criteria')),
                ('pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment_and_payments.pracownik', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Prices',
                'verbose_name_plural': 'Prices',
            },
        ),
        migrations.CreateModel(
            name='Harmonogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Date')),
                ('godziny', models.IntegerField(default=0, verbose_name='Hours')),
                ('wartosc', models.CharField(max_length=200, verbose_name='Value')),
                ('czy_urlop', models.BooleanField(verbose_name='Is vacation?')),
                ('pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment_and_payments.pracownik', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Harmonograms',
                'verbose_name_plural': 'Harmonograms',
            },
        ),
        migrations.CreateModel(
            name='Dzieci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=200, verbose_name='Name')),
                ('nazwisko', models.CharField(max_length=200, verbose_name='Surname')),
                ('wiek', models.IntegerField(default=0, verbose_name='Age')),
                ('pesel', models.IntegerField(default=0, verbose_name='PESEL')),
                ('pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment_and_payments.pracownik', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Kids',
                'verbose_name_plural': 'Kids',
            },
        ),
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=200, verbose_name='Type')),
                ('wystawiajacy', models.CharField(max_length=200, verbose_name='Signed By')),
                ('pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment_and_payments.pracownik', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Documents',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
