# Generated by Django 4.0 on 2021-12-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment_and_payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pracownik',
            name='drugie_imie',
            field=models.CharField(blank=True, max_length=200, verbose_name='Secound name'),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='nazwisko_panienskie',
            field=models.CharField(blank=True, max_length=200, verbose_name='Maiden name'),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='numer_konta_bankowego',
            field=models.DecimalField(decimal_places=0, max_digits=24, verbose_name='Bank account number'),
        ),
    ]
