# Generated by Django 3.1 on 2022-01-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment_and_payments', '0002_alter_pracownik_drugie_imie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubezpieczenie',
            name='rodzaj_ubezpieczenia',
            field=models.CharField(choices=[('compulsory', 'Compulsory'), ('voluntary', 'Voluntary')], default='voluntary', max_length=200, verbose_name='Type of issurance'),
        ),
        migrations.AlterField(
            model_name='wyksztalcenie',
            name='typ',
            field=models.CharField(choices=[('Higher', 'Higher'), ('Secondary', 'Secondary'), ('Basic', 'Basic')], default='Basic', max_length=200, verbose_name='Type'),
        ),
    ]
