# Generated by Django 3.1 on 2022-01-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment_and_payments', '0003_auto_20220112_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pracownik',
            name='pesel',
            field=models.DecimalField(decimal_places=0, max_digits=11, verbose_name='PESEL'),
        ),
    ]
