# Generated by Django 3.1 on 2022-01-16 15:33

from datetime import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employment_and_payments', '0004_auto_20220116_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubezpieczenie',
            name='kwota_ubezpieczenia',
            field=models.BigIntegerField(default=20000, verbose_name='insurance amount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='harmonogram',
            name='data',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.today)], verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='stan_cywilny',
            field=models.CharField(choices=[('married', 'married'), ('single', 'single'), ('widow', 'widow')], max_length=200, verbose_name='Marital status'),
        ),
        migrations.AlterField(
            model_name='szkolenie',
            name='data_rozpoczecia',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.today)], verbose_name='From date'),
        ),
        migrations.AlterField(
            model_name='szkolenie',
            name='data_zakonczenia',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.today)], verbose_name='To date'),
        ),
        migrations.AlterField(
            model_name='ubezpieczenie',
            name='data_do',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.today)], verbose_name='To date'),
        ),
        migrations.AlterField(
            model_name='ubezpieczenie',
            name='data_od',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.today)], verbose_name='From date'),
        ),
        migrations.AlterField(
            model_name='ubezpieczenie',
            name='rodzaj_ubezpieczenia',
            field=models.CharField(choices=[('obligatory', 'obligatory'), ('voluntary', 'voluntary')], default='voluntary', max_length=200, verbose_name='Type of issurance'),
        ),
        migrations.AlterField(
            model_name='urlop',
            name='data_rozpoczecia',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.today)], verbose_name='From date'),
        ),
        migrations.AlterField(
            model_name='urlop',
            name='data_wydania',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.today)], verbose_name='Release date'),
        ),
        migrations.AlterField(
            model_name='zwolnienielekarskie',
            name='data_rozpoczecia',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.today)], verbose_name='From date'),
        ),
        migrations.CreateModel(
            name='SwiadectwoPracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zwolnienia', models.DateTimeField(validators=[], verbose_name='Release date')),
                ('powod_zwolnienia', models.CharField(max_length=1000, verbose_name='Release reason')),
                ('ocena_pracownika', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employment_and_payments.ocenapracownika')),
            ],
            options={
                'verbose_name': 'Work certificate',
                'verbose_name_plural': 'Work certificates',
            },
        ),
    ]
