# Generated by Django 3.1 on 2022-01-16 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment_and_payments', '0006_auto_20220116_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocenapracownika',
            options={'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
    ]
