# Generated by Django 3.1 on 2022-01-16 15:52

import datetime
from time import timezone
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment_and_payments', '0008_swiadectwopracy_pracownik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harmonogram',
            name='data',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.date.today)], verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='swiadectwopracy',
            name='data_zwolnienia',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.date.today)], verbose_name='Release date'),
        ),
        migrations.AlterField(
            model_name='szkolenie',
            name='data_rozpoczecia',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.date.today)], verbose_name='From date'),
        ),
        migrations.AlterField(
            model_name='szkolenie',
            name='data_zakonczenia',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.date.today)], verbose_name='To date'),
        ),
        migrations.AlterField(
            model_name='ubezpieczenie',
            name='data_do',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.date.today)], verbose_name='To date'),
        ),
        migrations.AlterField(
            model_name='ubezpieczenie',
            name='data_od',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.date.today)], verbose_name='From date'),
        ),
        migrations.AlterField(
            model_name='urlop',
            name='data_rozpoczecia',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.date.today)], verbose_name='From date'),
        ),
        migrations.AlterField(
            model_name='urlop',
            name='data_wydania',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.date.today)], verbose_name='Release date'),
        ),
        migrations.AlterField(
            model_name='zwolnienielekarskie',
            name='data_rozpoczecia',
            field=models.DateTimeField(verbose_name='From date'),
        ),
    ]
