# Generated by Django 3.1 on 2022-01-16 16:08

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment_and_payments', '0009_auto_20220116_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zwolnienielekarskie',
            name='data_rozpoczecia',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.date.today)], verbose_name='From date'),
        ),
    ]
