# Generated by Django 3.1 on 2022-01-18 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employment_and_payments', '0011_auto_20220118_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swiadectwopracy',
            name='imie',
            field=models.CharField(default='', max_length=100, verbose_name='Employee name'),
        ),
        migrations.AlterField(
            model_name='swiadectwopracy',
            name='nazwisko',
            field=models.CharField(default='', max_length=100, verbose_name='Employee last name'),
        ),
        migrations.AlterField(
            model_name='swiadectwopracy',
            name='ocena_pracownika',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment_and_payments.ocenapracownika'),
        ),
        migrations.AlterField(
            model_name='swiadectwopracy',
            name='pracownik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment_and_payments.pracownik'),
        ),
    ]
