# Generated by Django 3.1 on 2022-01-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment_and_payments', '0013_auto_20220118_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swiadectwopracy',
            name='powod_zwolnienia',
        ),
        migrations.AddField(
            model_name='swiadectwopracy',
            name='ocena',
            field=models.CharField(default='none', max_length=1000, verbose_name='Rating'),
            preserve_default=False,
        ),
    ]
